### ISSUE TITLE
manual change required on auto-generated code due to char vs. char[] issue in json input files

### ISSUE THREAD

**Issue by jasoncpace** [albersgroup/picante#11]
https://github.com/albersgroup/picante/blob/master/picante-face-rtidds/src/main/resources/TransformTemplate.java

The json transform currently does not differentiate between char and char[]. char[] is assumed. If the data type in java is expecting char, there will be a compile error on the auto-generated transformers. One of two fixes are needed:

1) Source IDL should be changed so that char is actually char[1]
2) Groovy script which is producing json should differentiate between char and char[] data types.

**Comment by Reliquia33ad** [comment]
So I have a candidate change to the Groovy script to pull down the "Multiplicity" field during extract.   Now each parameter looks like this.
```
       {
            "name": "owningCountryCode",
            "type": "char",
            "multiplicity": 1
        },
        {
            "name": "tailNumber",
            "type": "char",
            "multiplicity": 16
        },
```

**Comment by Reliquia33ad** [comment]
It appears that when the GSON parses the JSON it is dropping the 'multiplicity' field.   On the assumption that the MessageType.class that picante is using is coming from Copperfield, I changed the Parameter class to include a multiplicity member variable.   That didn't seem to do the trick, so.....

**Comment by frizman21** [comment]
- [ ] make sure we if(obj instanceof MulticiplityElement) around the function call.
