### ISSUE TITLE
Make the RtiHelper static listing of SupportTypes no longer necessary

### ISSUE THREAD

**Issue by frizman21** [albersgroup/picante#23]

**Comment by Reliquia33ad** [comment]
When looking at how the "MessageType" strings related to class names...
`		typeSupport.put("Message", MessageTypeSupport.class);
		typeSupport.put("VehicleSteeringCommandType", VehicleSteeringCommandTypeTypeSupport.class);
		typeSupport.put("InertialStateType", InertialStateTypeTypeSupport.class);
...
		typeSupport.put("VehicleAuxiliaryStateType", VehicleAuxiliaryStateTypeTypeSupport.class);
		typeSupport.put("FACE::DM:pmc::cm::DataLinkControlCommandType", DataLinkControlCommandTypeTypeSupport.class);
`
Can the class name be assumed to be the last token of the MessageType String with 'TypeSupport.class' concatenated to the end?

**Comment by frizman21** [comment]
No PR linked in this card. Please advise...
