### ISSUE TITLE
explore the use of AWS support S3 wagon

### ISSUE THREAD

**Issue by frizman21** [albersgroup/picante#49]
https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-project-maven.html

**Comment by Reliquia33ad** [comment]
I went through the documentation for AWS SDK for java.   It seems to provide support for AWS services via java and you can use Maven to build to manage your dependencies.   What I did not see was an alternate Maven Wagon with an S3 back end.  This leads me to believe that we still need a 3rd party solution.

**Comment by Reliquia33ad** [comment]
Gov cloud repo can be found at http://nexus.albers.team:8081/
